name: festel
description: Demo project showing Stripe Checkout integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  webview_flutter: ^1.0.0
  js: ^0.6.2
  simple_animations: ^1.3.3
  flutter_styled_toast: ^1.2.1
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  fluttertoast: ^7.1.0
  cloud_firestore: ^2.0.0
  razorpay_flutter: ^1.2.3
  firebase_database: ^7.1.0
  settings_ui: ^1.0.0
  date_range_picker: ^1.0.5
  number_inc_dec: ^0.6.6
  random_date: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf

  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/





